name: stories.cities.inclusivedesign.ca__production

on:
  workflow_dispatch:
  push:
    branches:
      - stories-cities-production

env:
  PROJECT_ID: 6d4309f7
  PROJECT_SMOKETEST_URL: https://stories.cities.inclusivedesign.ca/stories

jobs:
  deploy:
    if: github.repository == 'fluid-project/sjrk-story-telling'

    runs-on: ubuntu-latest

    steps:
      - name: Deploy stack
        uses: appleboy/ssh-action@master
        with:
          host:           ${{ secrets.SSH_HOSTNAME }}
          username:       ${{ secrets.SSH_USERNAME }}
          key:            ${{ secrets.SSH_PRIVATE_KEY }}
          port:           ${{ secrets.SSH_PORT }}
          proxy_host:     ${{ secrets.SSH_PROXY_HOSTNAME }}
          proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
          proxy_key:      ${{ secrets.SSH_PROXY_PRIVATE_KEY }}
          proxy_port:     ${{ secrets.SSH_PROXY_PORT }}
          envs:     PROJECT_ID
          script: |
            cd /srv/$PROJECT_ID/src                                       && \
            git checkout stories-cities-production                        && \
            git pull                                                      && \
            source ../deploy.env                                          && \
            /usr/local/bin/docker-compose -p $PROJECT_ID                     \
                                          -f docker-compose.yml              \
                                          -f docker-compose.cloud.yml        \
                                          up --force-recreate --build -d

      - name: Wait
        run: sleep 15

      - name: Smoke test
        run: curl --location --no-buffer --retry 120 --retry-delay 1 $PROJECT_SMOKETEST_URL
